version: '3.5'

services:
  ldapman-web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker.cetcxl.local/ldapman-web:latest
    hostname: ld4pman-web
    ports:
      - "8080:80"
    restart: always
