version: '3.5'

services:
  ldapman-web:
    build:
      context: ./ldap-web
      dockerfile: Dockerfile
    image: ld4pman-web:1.3.8
    hostname: ld4pman-web
    ports:
      - "8080:80"
    restart: always
